### ISSUE TITLE
Understanding Rise Ratio

### ISSUE THREAD

**Issue by jellebuth** [bradleyboyuyang/ML-HFT#1]
I love the project. Well done! I am a High-Frequency Trader in the crypto market usign Hummingbot myself. I will do a similar project in the near future.

Could you explain in words what the rise ratio is and how this is measured. I could not figure that out via the code

Thanks!

**Comment by bradleyboyuyang** [comment]
The feature rise ratio here can be understood as a lagged return with a rolling period (in seconds) defined as the parameter "before_time", which can be tuned and set by yourself (like 360 seconds or more). For the time index that is larger than "before_time", we simply find the lagged price and then calculate a return as the factor value. But for the time index that is smaller than "before_time", there's no data previously with such a time lag, so using the beginning ask price (at 9:00) to calculate the lagged return would be enough.

In this project I only use the lagged return for ask_price1 as one feature since I think it's already informative enough, but you may also try for other price series like buy_price1 or mid-quote series. 

Anyway, sorry about the Chinese comment, and glad you are interested in the project.

**Comment by bradleyboyuyang** [comment]
> I love the project. Well done! I am a High-Frequency Trader in the crypto market usign Hummingbot myself. I will do a similar project in the near future.
> 
> Could you explain in words what the rise ratio is and how this is measured. I could not figure that out via the code
> 
> Thanks!

The feature rise ratio here can be understood as a lagged return with a rolling period (in seconds) defined as the parameter "before_time", which can be tuned and set by yourself (like 360 seconds or more). For the time index that is larger than "before_time", we simply find the lagged price and then calculate a return as the factor value. But for the time index that is smaller than "before_time", there's no data previously with such a time lag, so using the beginning ask price (at 9:00) to calculate the lagged return would be enough.

In this project I only use the lagged return for ask_price1 as one feature since I think it's already informative enough, but you may also try for other price series like buy_price1 or mid-quote series.

Anyway, sorry about the Chinese comment, and glad you are interested in the project.
